# Nombre de la aplicación para Eureka
spring.application.name=CONFIG-SERVER

# Puerto del Config Server
server.port=8888

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=10.2.1.203

# Activamos el perfil 'native' para leer la configuracion desde el sistema de archivos local
spring.profiles.active=native

# CLAVE: Ruta a la carpeta local que contiene los archivos de configuracion
spring.cloud.config.server.native.search-locations=file:///config-repo

# Configuracion de registro en Eureka
eureka.client.serviceUrl.defaultZone=http://10.2.1.203:8761/eureka
